# -*- coding: utf-8 -*-
"""Basic Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NMQvESgn80M3vRA39-ueDHnBfr7JJY2X
"""

def calculator():
    print("Simple Calculator")
    print("Available operations: +, -, *, /, %")

    while True:
        try:
            num1 = float(input("Enter first number: "))
            op = input("Enter operator (+, -, *, /, %): ")
            num2 = float(input("Enter second number: "))

            if op == '+':
                print(f"Result: {num1 + num2}")
            elif op == '-':
                print(f"Result: {num1 - num2}")
            elif op == '*':
                print(f"Result: {num1 * num2}")
            elif op == '/':
                print("Error: Division by zero!" if num2 == 0 else f"Result: {num1 / num2}")
            elif op == '%':
                print("Error: Modulus by zero!" if num2 == 0 else f"Result: {num1 % num2}")
            else:
                print("Invalid operator!")

            if input("Do you want to continue? (y/n): ").lower() != 'y':
                break
        except ValueError:
            print("Invalid input! Please enter valid numbers.")
        except Exception as e:
            print(f"An error occurred: {str(e)}")

if __name__ == "__main__":
    calculator()