# -*- coding: utf-8 -*-
"""Booleans and Conditions .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mY8zNhpUEcQ23XQmxnN6xmBSSif3xBp8
"""

GPA = float(input("Enter your GPA: "))

if GPA > 3.8:
  print("Full scholarship")
elif 3.5 < GPA < 3.79:
  print("Half scholarship")
elif GPA < 3.5:
  print("No scholarship")