# -*- coding: utf-8 -*-
"""Python Print Activity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JPyCAqvkXo432shNYU3XGt-MaHdjXBgp
"""

print("Welcome to Python Programming!\n" "Learning to code is fun!")

name = "Joshua Russel Uy"
age = "21"
location = "Tagbilaran City"

print(f"My name is {name} and I am {age} from {location}")

shoppingList = "Canned Goods", "Water", "Shirt", "Pants", "Fruits"
a,b,c,d,f = shoppingList
print("Shopping list:")
print(a)
print(b)
print(c)
print(d)
print(f)